# Generated by Django 5.1.4 on 2025-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0002_category_alter_book_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_surname', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
