# Generated by Django 5.1.4 on 2025-01-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0006_book_book_shelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_shelf',
            new_name='book_self',
        ),
    ]
