# Generated by Django 5.1.4 on 2025-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0007_rename_book_shelf_book_book_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_self',
        ),
        migrations.AddField(
            model_name='book',
            name='book_shelf',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
