# Generated by Django 5.1.4 on 2025-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0008_remove_book_book_self_book_book_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
