# Generated by Django 5.1.4 on 2025-01-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0009_book_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
    ]
