# Generated by Django 5.1.4 on 2025-01-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0010_remove_book_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_title', models.CharField(blank=True, max_length=250)),
                ('best_image', models.ImageField(blank=True, null=True, upload_to='book/')),
                ('best_description', models.TextField(blank=True, max_length=500, null=True)),
                ('best_price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
        ),
    ]
