# Generated by Django 5.1.4 on 2025-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0011_bestselling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(blank=True, max_length=250, null=250)),
                ('journal_image', models.ImageField(blank=True, null=True, upload_to='book/')),
                ('journal_description', models.TextField(blank=True, max_length=500, null=True)),
                ('journal_price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
        ),
    ]
