# Generated by Django 5.1.4 on 2025-01-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0012_journal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
