# Generated by Django 5.1.4 on 2025-01-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0015_alter_bestselling_best_image_alter_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
