# Generated by Django 5.1.4 on 2025-01-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0016_book_book_full_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_full_description',
        ),
    ]
