# Generated by Django 5.1.4 on 2025-01-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0017_remove_book_book_full_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_shelf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_title',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
