# Generated by Django 5.1.4 on 2025-01-31 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0018_remove_book_book_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appi.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book/'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_shelf',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_title',
            field=models.CharField(blank=True, max_length=250, null=250),
            preserve_default=250,
        ),
    ]
