# Generated by Django 5.1.4 on 2025-02-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0019_remove_book_rating_book_book_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_name', models.CharField(blank=True, max_length=250, null=True)),
                ('register_surname', models.CharField(blank=True, max_length=250, null=True)),
                ('register_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('register_password', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
