# Generated by Django 5.1.4 on 2025-02-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0020_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_jornual',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
